### ISSUE TITLE
Have different on extracting data from annotation fils

### ISSUE THREAD

**Issue by Tmoxic** [JohnPPinto/Object_Detection_Satellite_Imagery_Yolov8_DIOR#1]
Hello, I have a difficulty in re-implenting your code, when I do the extracting data from annotation files part, for the counting  the instance for every object class part, the instance in train set and test set are empty, they will have the following output: 
([{'filename': 'dior_data/JPEGImages-trainval\\00001.jpg',
   'split_type': 'JPEGImages-trainval\\00001.jpg',
   'width': 800,
   'height': 800,
   'objects': 'golffield'},
  {'filename': 'dior_data/JPEGImages-trainval\\00002.jpg',
   'split_type': 'JPEGImages-trainval\\00002.jpg',
   'width': 800,
   'height': 800,
   'objects': 'Expressway-toll-station, vehicle'},
  {'filename': 'dior_data/JPEGImages-trainval\\00003.jpg',
   'split_type': 'JPEGImages-trainval\\00003.jpg',
   'width': 800,
   'height': 800,
   'objects': 'trainstation'},
  {'filename': 'dior_data/JPEGImages-trainval\\00004.jpg',
   'split_type': 'JPEGImages-trainval\\00004.jpg',
   'width': 800,
   'height': 800,
   'objects': 'chimney'},
  {'filename': 'dior_data/JPEGImages-trainval\\00005.jpg',
   'split_type': 'JPEGImages-trainval\\00005.jpg',
   'width': 800,
   'height': 800,
   'objects': 'storagetank, vehicle'}],
 Counter(),
 Counter(),
 {})
Would you please help me the understand the issue? 
![issue](https://github.com/JohnPPinto/Object_Detection_Satellite_Imagery_Yolov8_DIOR/assets/133834709/67bae772-0700-47b3-9b7b-b08d43d9c831)

**Comment by John-Pinto** [comment]
The reason for no data in the object instance is because of the wrong path for images.
Check your filename and split_type: 
```
{'filename': 'dior_data/JPEGImages-trainval\00001.jpg',
'split_type': 'JPEGImages-trainval\00001.jpg',
'width': 800,
'height': 800,
'objects': 'golffield'}
```
In the filename, all the paths are considered after the forward slash, but you have a backslash which makes the path wrong: basically, your path indicates that a file called ```'JPEGImages-trainval\00001.jpg'``` is in the directory ```'dior_data'```. This also affects the split_type and also for collecting  Counter data for the object instance.

This can be solved, you need to check the code for ```image_data_file_list```, this list is providing the wrong path. Correct the slash and change it to: ```'dior_data/JPEGImages-trainval/00001.jpg'```

**Comment by Tmoxic** [comment]
Thank you so much, it fixed the problem

**Comment by John-Pinto** [comment]
You're welcome
